
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    depends_on:
      - qdrant
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - OLLAMA_HOST=ollama
    entrypoint: ["/app/scripts/wait-for-qdrant.sh", "qdrant:6333", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    entrypoint: ["/app/ollama_entrypoint.sh"]
    ports:
      - "11434:11434"
    volumes:
      - ./scripts:/app
      - ollama_data:/root/.ollama
    mem_limit: 6.5g

volumes:
  qdrant_data:
  ollama_data:
