apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knowledge-assistant-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Resource limits for free tier
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-instances: "10"
        run.googleapis.com/min-instances: "0"
        # Enable CPU allocation only during requests
        run.googleapis.com/cpu-throttling: "true"
        # Cloud SQL connection (if using Cloud SQL)
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:REGION:knowledge-assistant-db"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/knowledge-assistant-backend:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: knowledge-assistant-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: knowledge-assistant-secrets
              key: JWT_SECRET
        - name: QDRANT_HOST
          value: "https://knowledge-assistant-qdrant-HASH-uc.a.run.app"
        - name: QDRANT_PORT
          value: "443"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: knowledge-assistant-secrets
              key: GEMINI_API_KEY
        - name: CORS_ORIGINS
          value: "https://knowledge-assistant-frontend-HASH-uc.a.run.app"
        - name: JWT_LIFETIME_SECONDS
          value: "3600"
        - name: USER_REGISTRATION_ENABLED
          value: "true"
        - name: EMAIL_VERIFICATION_REQUIRED
          value: "false"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: data-volume
        emptyDir: {}
  traffic:
  - percent: 100
    latestRevision: true