# Cloud SQL Configuration for Knowledge Assistant
# This file defines the Cloud SQL instance and database configuration

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: knowledge-assistant-db
spec:
  databaseVersion: POSTGRES_15
  region: us-central1
  settings:
    tier: db-f1-micro  # Free tier eligible
    availabilityType: ZONAL
    diskSize: 10  # GB - minimum for free tier
    diskType: PD_HDD
    diskAutoresize: true
    diskAutoresizeLimit: 20  # GB - stay within free tier limits
    backupConfiguration:
      enabled: true
      startTime: "03:00"  # 3 AM UTC
      retainedBackups: 7
      transactionLogRetentionDays: 7
    ipConfiguration:
      ipv4Enabled: true
      authorizedNetworks: []  # Cloud Run will connect via private IP
      requireSsl: true
    maintenanceWindow:
      day: 7  # Sunday
      hour: 4  # 4 AM UTC
      updateTrack: stable
    userLabels:
      app: knowledge-assistant
      environment: production
      tier: free

---

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: knowledge-assistant-main-db
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: knowledge-assistant-db

---

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: knowledge-assistant-user
spec:
  instanceRef:
    name: knowledge-assistant-db
  password:
    valueFrom:
      secretKeyRef:
        name: knowledge-assistant-secrets
        key: DB_PASSWORD