apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knowledge-assistant-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Resource limits for free tier
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-instances: "10"
        run.googleapis.com/min-instances: "0"
        # Enable CPU allocation only during requests
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/knowledge-assistant-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: VITE_API_BASE_URL
          value: "https://knowledge-assistant-backend-HASH-uc.a.run.app"
        - name: VITE_API_TIMEOUT
          value: "30000"
        - name: VITE_ENABLE_REGISTRATION
          value: "true"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
  traffic:
  - percent: 100
    latestRevision: true