# IAM Configuration for Cloud Run Services
# This file defines the service accounts and IAM roles needed for the Knowledge Assistant application

# Service Account for Backend Service
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: knowledge-assistant-backend-sa
  namespace: default
spec:
  displayName: "Knowledge Assistant Backend Service Account"
  description: "Service account for Knowledge Assistant backend with minimal required permissions"

---

# Service Account for Qdrant Service
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: knowledge-assistant-qdrant-sa
  namespace: default
spec:
  displayName: "Knowledge Assistant Qdrant Service Account"
  description: "Service account for Qdrant vector database service"

---

# IAM Policy Binding for Backend Service Account - Cloud SQL Client
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: backend-cloudsql-client
spec:
  member: serviceAccount:knowledge-assistant-backend-sa@PROJECT_ID.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: PROJECT_ID

---

# IAM Policy Binding for Backend Service Account - Secret Manager Accessor
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: backend-secret-accessor
spec:
  member: serviceAccount:knowledge-assistant-backend-sa@PROJECT_ID.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: PROJECT_ID

---

# IAM Policy Binding for Backend Service Account - Cloud Run Invoker (for internal service communication)
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: backend-run-invoker
spec:
  member: serviceAccount:knowledge-assistant-backend-sa@PROJECT_ID.iam.gserviceaccount.com
  role: roles/run.invoker
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: PROJECT_ID

---

# IAM Policy Binding for Qdrant Service Account - Basic Cloud Run permissions
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: qdrant-run-invoker
spec:
  member: serviceAccount:knowledge-assistant-qdrant-sa@PROJECT_ID.iam.gserviceaccount.com
  role: roles/run.invoker
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: PROJECT_ID