# Secret Manager Configuration for Knowledge Assistant
# This file defines the secrets needed for the application

apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: knowledge-assistant-secrets
spec:
  secretId: knowledge-assistant-secrets
  replication:
    automatic: true
  labels:
    app: knowledge-assistant
    environment: production

---

# Secret versions will be created separately via gcloud CLI or console
# The following secrets need to be stored:
# - JWT_SECRET: A secure random string for JWT token signing
# - DATABASE_URL: PostgreSQL connection string for Cloud SQL
# - GEMINI_API_KEY: Google Gemini API key for LLM functionality
# - DB_PASSWORD: Database password for the Cloud SQL user

# Example secret creation commands (to be run after deployment):
# gcloud secrets versions add knowledge-assistant-secrets --data-file=secrets.json
# 
# Where secrets.json contains:
# {
#   "JWT_SECRET": "your-super-secure-jwt-secret-key-change-this-in-production",
#   "DATABASE_URL": "postgresql+asyncpg://knowledge-assistant-user:PASSWORD@/knowledge-assistant-main-db?host=/cloudsql/PROJECT_ID:us-central1:knowledge-assistant-db",
#   "GEMINI_API_KEY": "your-gemini-api-key",
#   "DB_PASSWORD": "your-secure-database-password"
# }